version: '3'

tasks:
  app:start:
    cmds:
      ##
      # NOTE: Start `yarn start` for code-notes (rules) as well.
      # See `config/initializers/static.rb`.
      #
      # NOTE: Open `http://localhost:3000/`
      #
      - bundle install
      - bundle exec rails db:migrate
      - cd static_sites/code-notes && yarn install && yarn build
      - rm -rf app/views/static
      - mkdir -p app/views/static
      - cp -r static_sites/code-notes/public app/views/static/rules
      - bundle exec rails server
    interactive: true

  app:rules:start:
    cmds:
      ##
      # NOTE: Open `http://localhost:8000/`
      #
      - cd static_sites/code-notes && yarn install && yarn dev

  test:
    cmds:
      - bundle exec rspec

  deps:install:
    cmds:
      - bundle install
      - cd static_sites/code-notes && yarn install

  ##
  #
  #
  local_production:app:start:
    cmds:
      - RAILS_ENV=production bundle exec rails db:migrate
      - RAILS_ENV=production bundle exec rake assets:precompile
      - bundle exec rails server -e production

  ##
  #
  #
  local_production:app:logs:
    cmds:
      - mkdir -p log && touch log/production.log && tail -f log/production.log

  ##
  # https://fly.io/docs/rails/the-basics/deployments/#running-migrations
  #
  production:app:db:migrate:
    cmds:
      - fly ssh console -C "app/bin/rails db:migrate"

  ##
  # https://fly.io/docs/rails/getting-started/
  #
  production:app:deploy:
    cmds:
      - fly deploy

  ##
  # https://fly.io/docs/rails/the-basics/run-tasks-and-consoles/#rails-console
  #
  # NOTE: Make sure you have executed `fly launch` if you have a new application.
  #
  production:app:console:
    cmds:
      - fly ssh console -C "app/bin/rails console"

  ##
  # FIX: Does NOT work since `fly ssh console -C` does NOT wait `tail -f` to complete, it exits immediately.
  # Use `task production:env:console` or `task production:app:output` instead.
  #
  # https://fly.io/docs/rails/the-basics/run-tasks-and-consoles/#rails-console
  #
  # IMPORTANT: Make sure `RAILS_LOG_TO_STDOUT` env var is `false` in `Dockerfile.production`.
  # Use `task production:app:output` if NOT.
  #
  # NOTE: `/app/app` is actually Rails `app`, that is why `/app/log`, not just `log`.
  # `/app` is created by fly.
  #
  production:app:logs:
    cmds:
      - fly ssh console -C "touch /app/log/production.log && tail -f /app/log/production.log"

  ##
  # https://fly.io/docs/rails/the-basics/run-tasks-and-consoles/#rails-console
  #
  # IMPORTANT: Make sure `RAILS_LOG_TO_STDOUT` env var is `true` in `Dockerfile.production`.
  # Use `task production:app:logs` if NOT.
  #
  production:app:output:
    cmds:
      - fly logs

  ##
  # https://fly.io/docs/rails/the-basics/deployments/#run-ad-hoc-tasks-after-deploying
  #
  production:env:console:
    cmds:
    - fly ssh console
