##
# This file was autogenerated by `bundle exec rails g static_rails:initializer`.
#
StaticRails.config do |config|
  ##
  # NOTE: Config examples:
  # - https://github.com/testdouble/static-rails/blob/main/lib/generators/templates/static.rb
  # - https://github.com/testdouble/static-rails/blob/main/example/config/initializers/static.rb
  #
  config.sites = [
    {
      name: "rules",
      source_dir: "static_sites/code-notes",
      ##
      # IMPORTANT: Must be kept in sync with `config/initializers/static.rb`.
      #
      url_root_path: "/rules",
      start_server: !Rails.env.production?,
      env: {},
      server_command: "yarn build && yarn start",
      server_host: "localhost",
      server_port: "9000",
      server_path: "/",
      compile_command: "yarn install && yarn build",
      ##
      # NOTE: `gatsby build` generates `public` folder.
      # - https://www.gatsbyjs.com/docs/reference/gatsby-project-structure/#folders
      # - https://www.gatsbyjs.com/docs/conceptual/overview-of-the-gatsby-build-process/#understanding-gatsby-build-build-time
      #
      compile_dir: "static_sites/code-notes/public",
      compile_404_file_path: "static_sites/code-notes/public/404/index.html"
    }
  ]
end
